import {StyleSheet} from 'react-native'
import colors from './colors'

const styles = StyleSheet.create({
    container: {
      display: 'flex',
      flex: 1,
      flexDirection: 'column',
      justifyContent: 'center',
      paddingTop: 20,
      alignItems:'center',
      backgroundColor: colors.background,
      // marginTop: StatusBar.currentHeight ||0,
      minHeight: 770
    },
    container1: {
      display: 'flex',
      flex: 1,
      height: 'auto',
      flexDirection: 'column',
    },
    container2: {
      display: 'flex',
      justifyContent: 'center',
      alignItems:'center',
      flexDirection: 'row',
      paddingLeft: 5,
      margin: 5,
      borderColor: colors.borderinput,
      borderWidth: 1,
      borderRadius: 25,
    },
    container3: {
      flex:1,
      flexDirection: 'row',
      alignItems: 'flex-end',
    },
    container4: {
      width: 350,
      marginTop: 8,
      paddingBottom: 4,
      alignItems: 'center',
      borderRadius: 10,
      borderTopWidth: 1,
      borderColor: colors.bordercontainer,
    },
    container5:{
      display: 'flex',
      flexDirection: 'row',
    },
    container6: {
      alignItems: 'center',
      backgroundColor: colors.background,
    },
    container7: {
      paddingBottom: 4,
      alignItems: 'center',
      backgroundColor: colors.background,
    },
    item0: {
      backgroundColor: colors.backgroundinput,
      padding: 4,
      marginVertical: 4,
      marginHorizontal: 8,
      borderWidth: 0.2,
      borderColor: colors.bordercontainer,
    },
    item1: {
      flex: 1,
      backgroundColor: colors.background,
      padding: 4,
      marginVertical: 4,
      marginHorizontal: 8,
      borderWidth: 0.2,
      borderColor: colors.bordercontainer,
    },
    inputBox: {
      width: 200,
      paddingHorizontal: 8,
      margin: 4,
      color: colors.texte,
    },
    inputBox1: {
        width: 100,
        paddingHorizontal: 8,
        margin: 8,
        color: colors.texte,
        borderColor: colors.borderinput,
        borderRadius: 25,
    },
    // inputBox2: {
    //   width: 100,
    //   paddingHorizontal: 8,
    //   margin: 8,
    //   color: colors.texte,
    //   borderColor: colors.borderinput,
    //   borderRadius: 25,
    // },
    button: {
      width: 250,
      paddingHorizontal: 16,
      paddingVertical: 8,
      margin: 8,
      backgroundColor: colors.buttonlogin,
      borderColor: colors.borderinput,
      borderWidth: 1,
      borderRadius: 25,
      color: colors.texte,
      textAlign: 'center',
    },
    button1: {
      width: 300,
      margin: 8,
      fontSize: 25,
      paddingHorizontal: 8,
      backgroundColor: colors.button,
      borderColor: colors.borderinput,
      borderRadius: 25,
      color: colors.texte,
      textAlign: 'center',
    },
    text: {
        margin: 8,
        paddingHorizontal: 8,
        color: colors.texte,
        justifyContent: 'center',
        textAlignVertical: 'center',
    },
    text1: {
      width: 150,
      // margin: 0,
      // paddingHorizontal: 0,
      color: colors.texte,
      textAlign: 'center',
      // textAlignVertical: 'center',
    },
    text2: {
      fontSize: 20,
      paddingBottom: 8,
      paddingTop: 8,
      color: colors.texte,
      textAlignVertical: 'center',
    },
    text3: {
      width: 120,
      color: colors.texte,
    },
    text4: {
      width: 120,
      height: 45,
      color: colors.texte,
      borderColor: colors.borderinput,
      borderWidth: 0,
      borderRadius: 25,
      textAlignVertical: 'center',
    },
    textlien: {
      margin: 8,
      paddingHorizontal: 8,
      color: colors.texte,
      textAlignVertical: 'center',
    },
    signupcont: {
      flexDirection: 'row',
      marginBottom: 8,
    },
    signuptext: {
      paddingHorizontal: 8,
      paddingVertical: 8,
      color: colors.signuptext,
      textAlignVertical: 'center',
    },
    accounttext: {
      paddingHorizontal: 8,
      color: colors.accounttext,
      textAlignVertical: 'center',
    },
    errMessage: {
      margin: 4,
      height: 48,
      color: colors.accounttext,
      justifyContent: 'center',
      alignItems:'center',
    },
    error: {
      color: "#E9446A",
      textAlignVertical: 'center',
    },
    back: {
      position: "absolute",
      top: 48,
      left: 42,
      width: 42,
      height: 42,
      borderRadius: 16,
      backgroundColor: "rgba(21, 22, 48, 0.1)",
      alignItems: "center",
      justifyContent: "center"
    },
    title: {
      fontSize: 18,
      color: colors.texte,
    },
    title1: {
      fontSize: 14,
      color: colors.signuptext
    },
  })

export default styles